### ISSUE TITLE
inconsistent window opening side with option 'splitright'

### ISSUE THREAD

**Issue by AvianY** [Konfekt/vim-scratchpad#1]
If the option 'splitright' is set, the scratchpad will open on the right side the first time, but after that it will only open on the left side.

**Comment by Konfekt** [comment]
Ok, thanks for reporting. I am not sure why I forced it to open on the left. Check the latest commit and let me know how it works out for you.

**Comment by AvianY** [comment]
Now it works perfectly :D

**Comment by Konfekt** [comment]
Great!
