### ISSUE TITLE
Feature request: add a separate mapping for horizontal split

### ISSUE THREAD

**Issue by AvianY** [Konfekt/vim-scratchpad#2]
As the title says, it would be very practical to be able to open a scratchpad in a horizontal split instead when the window is narrow and tall.

**Comment by Konfekt** [comment]
Dear @AvianY , now there's a check depending on the window ration which split is most appropriate. Please give it a test ride. You can tune the values by changing `5` and `2` in 

https://github.com/Konfekt/vim-scratchpad/commit/ee77088b798b18c0fbfd828a6f2257e63ec97dc5#diff-373eca5581fc1e025c5490bcf201b33fR32

**Comment by AvianY** [comment]
That's even better! I tried it with different ratios and I think it works quite nicely :)

**Comment by Konfekt** [comment]
Yeah, now I noticed that there was an oversight when opening the scratchpad for the first time. It should be fixed now. If you think the ratios should be different, let me know! For the meanwhile, let's close the issue. Thanks for bringing it up!
