### ISSUE TITLE
Consist Filetyping

### ISSUE THREAD

**Issue by 1094** [Konfekt/vim-scratchpad#3]
I would like all scratchpads to default to the same filetype (I'm thinking I can use modelines for the off chance I need it to be something different); is it possible to do that?

**Comment by Konfekt** [comment]
Yes, try
```vim
nnoremap <silent> dsp :<c-u>call scratchpad#ToggleScratchPad('text')<CR>
```
where `dsp` is the binding and `text` is the file type.

**Comment by Konfekt** [comment]
You can also customize it by the variable
```vim
let g:scratchpad_ftype = ''
```
by the latest commit.
