### ISSUE TITLE
Opening scratchpad disables syntax highlight in previous buffer

### ISSUE THREAD

**Issue by AvianY** [Konfekt/vim-scratchpad#4]
as the title says
I open the scratchpad and the python file that I had open before that turns color-less. I can fix it by running the ```:e``` command, but it's annoying

**Comment by Konfekt** [comment]
Is that a novelty, did this only occur with the latest commit?

**Comment by Konfekt** [comment]
Please check the latest commit.

**Comment by AvianY** [comment]
now it's all right. good job ;)
